# Generated by Django 4.1.5 on 2023-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
