# Generated by Django 4.1.5 on 2023-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='post',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Логист', 'Логист'), ('Руководитель', 'Руководитель'), ('Стажер', 'Стажер')], default='Стажер', max_length=30),
        ),
    ]
