# Generated by Django 4.1.5 on 2023-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userinformation_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
