# Generated by Django 4.1.5 on 2023-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userinformation_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='name',
            field=models.CharField(default='timezone.own.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='surname',
            field=models.CharField(default='timezone.own.', max_length=20),
            preserve_default=False,
        ),
    ]
