# Generated by Django 4.1.5 on 2023-02-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userinformation_name_userinformation_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
