# Generated by Django 4.1.5 on 2023-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='commentary',
            field=models.ManyToManyField(to='tasks.comments'),
        ),
    ]
