# Generated by Django 4.1.5 on 2023-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_likes_dnot_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dnot_likes',
            field=models.ManyToManyField(to='tasks.dnot_likes'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='likes',
            field=models.ManyToManyField(to='tasks.likes'),
        ),
    ]
