# Generated by Django 4.1.5 on 2023-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_dnot_likes_tasks_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image_dlike',
            field=models.ImageField(blank=True, default='image_likes/dlike.png', null=True, upload_to='image_likes/'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='image_like',
            field=models.ImageField(blank=True, default='image_likes/like.png', null=True, upload_to='image_likes/'),
        ),
    ]
