# Generated by Django 4.1.5 on 2023-03-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_trans', '0003_alter_carrier_name_editcarrier'),
        ('tasks', '0007_tasks_image_dlike_tasks_image_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='carrier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list_trans.editcarrier'),
            preserve_default=False,
        ),
    ]
