# Generated by Django 4.1.5 on 2023-03-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasks_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='carrier',
        ),
    ]
