# Generated by Django 4.1.5 on 2023-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_tasks_carrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='car',
            new_name='transport_requirement',
        ),
        migrations.AddField(
            model_name='tasks',
            name='price_client',
            field=models.IntegerField(default=0),
        ),
    ]
