# Generated by Django 4.1.5 on 2023-03-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userinformation_status'),
        ('tasks', '0011_rename_car_tasks_transport_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='logist',
            field=models.ForeignKey(limit_choices_to={'post': 'Логист'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userinformation'),
        ),
    ]
