# Generated by Django 4.1.5 on 2023-03-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userinformation_status'),
        ('tasks', '0013_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'post': 'Менеджер'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tasks', to='profiles.userinformation'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='logist',
            field=models.ForeignKey(limit_choices_to={'post': 'Логист'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_tasks', to='profiles.userinformation'),
        ),
    ]
