# Generated by Django 4.1.5 on 2023-03-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userinformation_status'),
        ('tasks', '0014_tasks_manager_alter_tasks_logist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'post': 'Руководитель'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tasks', to='profiles.userinformation'),
        ),
    ]
