# Generated by Django 4.1.5 on 2023-03-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_tasks_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='manager',
        ),
    ]
