# Generated by Django 4.1.5 on 2023-03-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_trans', '0002_rename_сarrier_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='EditCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сompany_name', models.CharField(choices=[('opt', 'opt'), ('Optimum', 'Optimum')], max_length=30)),
                ('brand_and_number_car', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price_car', models.IntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_trans.carrier')),
            ],
        ),
    ]
