# Generated by Django 4.1.5 on 2023-03-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_trans', '0004_editcarrier_tasks_alter_editcarrier_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editcarrier',
            name='сompany_name',
        ),
    ]
