# Generated by Django 4.1.5 on 2023-03-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_trans', '0005_remove_editcarrier_сompany_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='editcarrier',
            old_name='name',
            new_name='name_driver',
        ),
        migrations.RenameField(
            model_name='editcarrier',
            old_name='price_car',
            new_name='price_carrier',
        ),
    ]
